### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by lihaicheng7003** [biowdl/germline-DNA#103]
Hello, please how to test, the tests folder is given in the repository, but it seems that it is not stated in the docs。
![image](https://github.com/biowdl/germline-DNA/assets/61043072/d5deb0dd-15a4-4669-8e7d-0d789200619c)

**Comment by rhpvorderman** [comment]
The short version is to install `miniwdl` and `pytest-workflow` through conda and to run pytest from the git root directory. 
Does that help you?

**Comment by lihaicheng7003** [comment]
That helped me. Thanks.
